addSbtPlugin("org.foundweekends"   % "sbt-bintray"            % "0.5.4")
addSbtPlugin("com.typesafe.sbt"    % "sbt-site"               % "1.3.2")
addSbtPlugin("com.typesafe.sbt"    % "sbt-ghpages"            % "0.6.2")
addSbtPlugin("com.eed3si9n"        % "sbt-unidoc"             % "0.4.1")
addSbtPlugin("org.tpolecat"        % "tut-plugin"             % "0.6.3")
addSbtPlugin("com.typesafe.sbt"    % "sbt-git"                % "0.9.3")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest"            % "0.7.2")
addSbtPlugin("com.github.gseitz"   % "sbt-release"            % "1.0.8")
